### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by s-hfarooq** [KevinVerre/kevinverre#1]
- On line 55 of index.html, the word `Illinois` is misspelled
- On line 135 of index.html, `It's collection of` should be `It's a collection of`
- The link in README.md does not work. It should be `(https://www.kevinverre.com)` instead of `(www.kevinverre.com)`

**Comment by KevinVerre** [comment]
Thanks!

**Comment by KevinVerre** [comment]
Closing because I made all three changes.
